name: Tag Triggered Workflow

on:
  push:
    branches: [ develop ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta"
  pull_request:
    branches: [ develop, main ]
    types: [ opened, reopened, synchronize, ready_for_review ]
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Message
      run: echo "Workflow triggered by tag"
